run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - gocritic
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - nilerr
    - bodyclose
    - exhaustive
    - prealloc
    - revive

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
  revive:
    rules:
      - name: exported
        arguments:
          - "checkPrivateReceivers"
      - name: unused-parameter
      - name: unreachable-code
      - name: context-as-argument
      - name: error-return
  exhaustive:
    default-signifies-exhaustive: true
  goimports:
    local-prefixes: arsen

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
